### ISSUE TITLE
我这怎么提示用swift3.0版本？？？

### ISSUE THREAD

**Issue by GarthGit** [choiceyou/FWSegmentedControl#3]
Unsupported Swift Version
The target “FWSegmentedControl” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.

**Comment by GarthGit** [comment]
还要迁移代码，还需要用Xcode8.0版本的

**Comment by GarthGit** [comment]
Check dependencies

The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

**Comment by choiceyou** [comment]
目前是swift4.0，因此需要xcode9以上哦
